<h3>Listado de tareas</h3>
<div class="container">
	<a href="<?php echo APP_URL.'categorias/agregar'; ?>">
		<button class="btn btn-sm btn-success">Agregar</button>
	</a>
	<table class="table table-sm mg-top-10">
		<thead class="thead-light">
			<tr>
				<th>Id</th>
				<th>Descripcion</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>			
			<?php foreach ($this->categorias as $categoria): ?>
				<tr>
					<td><?php echo $categoria["id"]; ?></td>
					<td><?php echo $categoria["nombre"]; ?></td>
					<td>
						<a href="<?php echo APP_URL.'categorias/editar/'.$categoria["id"]; ?>">
							<button class="btn btn-sm btn-primary">
								<i class="fa fa-pen"></i>
							</button>
						</a>
						<a href="<?php echo	APP_URL.'categorias/eliminar/'.$categoria["id"]; ?>">
							<button class="btn btn-sm btn-danger">
								<i class="fa fa-trash"></i>
							</button>
						</a>
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>
